version: "3"
services:
  vpn:
    image: bubuntux/nordvpn
    restart: always
    network_mode: bridge
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.rp_filter=2
    devices:
      - /dev/net/tun
    environment:
      - USER=username
      - "PASS=pas$word"
      - CONNECT=United_States
      - TECHNOLOGY=NordLynx
      - NETWORK=192.168.1.0/24
      - "DNS=1.1.1.1,1.0.0.1"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9091:9091
      - 31415:31415
      - 31415:31415/udp

  transmission:
    image: linuxserver/transmission
    restart: always
    depends_on:
      - vpn
    network_mode: service:vpn
    environment:
      - PUID=1000
      - PGID=1000
      - TRANSMISSION_WEB_HOME=/combustion-release/
      - USER=theponds
      - PASS=riversong
      - TZ=Europe/Zurich
    volumes:
      - ./data/config:/config
      - ./data/downloads:/downloads
      - ./data/watch:/watch
