version: "3"
services:
  transmission:
    image: linuxserver/transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TRANSMISSION_WEB_HOME=/combustion-release/
    volumes:
      - ./data/config:/config
      - ./data/downloads:/downloads
      - ./data/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: always
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 5
        window: 180s

