---
version: "2.1"
services:
  piwigo:
    image: ghcr.io/linuxserver/piwigo
    container_name: piwigo
    environment:
      - PUID=1000
      - PGID=1000
      - "TZ=${TIMEZONE}"
    volumes:
      - ./data/piwigo/config:/config
    ports:
      - 8081:80
    restart: unless-stopped
