---
version: "2.1"
services:
  syncthing:
    image: ghcr.io/linuxserver/syncthing
    container_name: syncthing
    hostname: "${HOSTNAME}"
    environment:
      - PUID=1000
      - PGID=1000
      - "TZ=${TIMEZONE}"
    volumes:
      - "${SYNCTHING_DIR_CONFIG}:/config"
      - "${SYNCTHING_DIR_DATA1}:/data1"
    ports:
      - 8384:8384
      - 22000:22000
      - 21027:21027/udp
    restart: unless-stopped
