version: "3"
services:
  vpn:
    image: bubuntux/nordvpn
    network_mode: bridge
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.rp_filter=2
    devices:
      - /dev/net/tun
    environment:
      - USER=username
      - "PASS=pas$word"
      - CONNECT=United_States
      - TECHNOLOGY=NordLynx
      - NETWORK=192.168.1.0/24
      - "DNS=1.1.1.1,1.0.0.1"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9091:9091
      - 31415:31415
      - 31415:31415/udp
#    deploy:
#      restart_policy:
#        condition: any
#        delay: 5s
#        max_attempts: 5
#        window: 180s

  transmission:
    image: linuxserver/transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TRANSMISSION_WEB_HOME=/combustion-release/
    volumes:
      - ./data/config:/config
      - ./data/downloads:/downloads
      - ./data/watch:/watch
#    deploy:
#      restart_policy:
#        condition: any
#        delay: 5s
#        max_attempts: 5
#        window: 180s

